module.exports = {
    SITES_USER_CREATION: 'SITES_USER_CREATION',
    SITES_USER_BASIC_INFO_UPDATE: 'SITES_USER_BASIC_INFO_UPDATE',
    SITES_USER_SMS_SETTINGS_UPDATE: 'SITES_USER_SMS_SETTINGS_UPDATE',
    SITES_SITE_COMPANY_DATA_UPDATE: 'SITES_SITE_COMPANY_DATA_UPDATE',
    SITES_USER_CHANGE_PASSWORD: 'SITES_USER_CHANGE_PASSWORD',
};
