export const eventTypeDisplayMap = {
    healthCheck: 'HEALTH CHECK',
    physicalTest: 'PHYSICAL TEST',
    nurseCallActivate: 'NURSE CALL ACTIVATE',
    nurseCallCancel: 'NURSE CALL CANCEL',
    nurseCallEnd: 'NURSE CALL END',
    nurseCall: 'NURSE CALL REPORT',
    nurseCallReport: 'NURSE CALL REPORT',
    evacuationActivate: 'EVACUATION ACTIVATE',
    evacuationCancel: 'EVACUATION CANCEL',
    evacuation: 'EVACUATION REPORT',
    evacuationReport: 'EVACUATION REPORT',
    evacuationAcknowledge: 'EVACUATION ACKNOWLEDGE',
    evacuationEnd: 'EVACUATION END',
    callout: 'CALLOUT',
    callOut: 'CALLOUT',
    nurseCallAccept: 'NURSE CALL ACCEPT',
    nurseCallDecline: 'NURSE CALL DECLINE',
    nurseCallAcceptDetail: 'NURSE CALL ACCEPT DETAIL',
    nurseCallDeclineDetail: 'NURSE CALL DECLINE DETAIL',
    faultDescription: 'FAULT DESCRIPTION',
    changeRename: 'RENAME/CHANGE LOCATION',
    enableDevice: 'ENABLE DEVICE',
    disableDevice: 'DISABLE DEVICE',
    removeDevice: 'REMOVE DEVICE',
    addDevice: 'ADD DEVICE',
    statusChange: 'STATUS CHANGE',
    systemStart: 'SYSTEM START',
    systemExit: 'SYSTEM EXIT',
    forcerestart: 'RESTART REMOTELY',
    initializeDevice: 'INITIALIZE DEVICE',
    initializeDeviceSuccess: 'INITIALIZE DEVICE SUCCESS',
    initializeDeviceFail: 'INITIALIZE DEVICE FAIL',
    testSirenOn: 'TEST SIREN ON',
    testSirenOff: 'TEST SIREN OFF',
    databaseStats: 'DATABASE STATS',
    applicationNotResponding: 'ANR CRASH',
    evacuationWarning: 'EVACUATION WARNING',
    autoTestSiren: 'SIREN AUTO TEST',
    deactivateSirensByUser: 'DEACTIVATE SIRENS',
    lockdownActivate: 'LOCKDOWN ACTIVATE',
    lockdownEnd: 'LOCKDOWN END',
    lockdownEscalate: 'LOCKDOWN ESCALATE',
    siteUserDelete: 'SITE USER DELETE',
};
